openapi: 3.0.0
info:
  title: Login Page
  version: "1.0.0"
paths:
  /login:
    post:
      summary: Login Page
      description: |
        Simulated login form for username and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Logged in successfully
        '401':
          description: Unauthorized
